from langgraph.graph import StateGraph, START, END

from agents.supervisor import (
    supervisor,
    State,
    route_next_agent,
)

from agents.rag_agent import create_rag_agent
from agents.research_agent import research_agent
from agents.analysis_agent import analysis_agent
from agents.final_agent import final_agent

from rag.pipeline.generation_pipeline import create_rag_pipeline


def build_graph(chunks):
    """
    Build the multi-agent graph.

    chunks:
        Chunks generated by ingest_document(...)
    """

    # Build RAG once
    rag = create_rag_pipeline(chunks)

    # Create RAG agent using the existing RAG pipeline
    rag_agent = create_rag_agent(rag)

    # Create graph
    builder = StateGraph(State)

    # ----------------
    # Nodes
    # ----------------

    builder.add_node("supervisor", supervisor)
    builder.add_node("rag", rag_agent)
    builder.add_node("research", research_agent)
    builder.add_node("analysis", analysis_agent)
    builder.add_node("final", final_agent)

    # ----------------
    # Entry
    # ----------------

    builder.add_edge(START, "supervisor")

    # ----------------
    # Supervisor routing
    # ----------------

    builder.add_conditional_edges(
        "supervisor",
        route_next_agent,
        {
            "rag": "rag",
            "research": "research",
            "analysis": "analysis",
            "final": "final",
        },
    )

    # ----------------
    # Workers → Supervisor
    # ----------------

    builder.add_edge("rag", "supervisor")
    builder.add_edge("research", "supervisor")
    builder.add_edge("analysis", "supervisor")

    # ----------------
    # Final → END
    # ----------------

    builder.add_edge("final", END)

    return builder.compile()